### ISSUE TITLE
Case sensitive ordering

### ISSUE THREAD

**Issue by jcfinnerup** [graphile-contrib/pg-order-by-related#18]
Is there any way to make the ordering of strings case insensitive :) ?

**Comment by mattbretl** [comment]
String ordering is influenced by your collation settings, and PostgreSQL relies on the underlying OS implementation, so unfortunately you'll get different results on Debian/Ubuntu vs. on a Mac. Here's a relevant discussion of the issue: https://stackoverflow.com/questions/15427529/alphanumeric-case-in-sensitive-sorting-in-postgres

With that in mind, I don't want to add case-sensitive/insensitive options to this plugin because the end result will depend on the OS. Feel free to reach out on Discord (https://discord.gg/graphile) if you have any questions about this.. it's a tricky subject.

**Comment by benjie** [comment]
I recommend you use the PostgreSQL `CITEXT` type here, though I don't know if it solves the collation issues.
